
version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: harryest/capstone:latest
    container_name: autoscheduler-web
    ports:
      - "8080:8080"
    networks:
      - capstone_network
networks:
  capstone_network:
    driver: bridge